---
- hosts : Spine-switches
  connection : local
  gather_facts : no

  tasks :
  - name : "Basic Configuration"
    dellos9_config :
        #commands : ['route-map spine-leaf permit 10', 'match ip address spine-leaf', 'exit']
        commands:
          - route-map spine-leaf permit 10
          - match ip address spine-leaf
        provider : "{{cli}}"

  roles :
      - Dell-Networking.dellos-pl
      - Dell-Networking.dellos-bgp

- hosts : Leaf-switches
  connection : local
  gather_facts : no

  tasks :
  - name : "Basic Configuration"
    dellos9_config :
        #commands : ['route-map spine-leaf permit 10', 'match ip address spine-leaf', 'exit']
        commands:
          - route-map spine-leaf permit 10
          - match ip address spine-leaf
        provider : "{{cli}}"

  roles :
      - Dell-Networking.dellos-pl
      - Dell-Networking.dellos-bgp
      - Dell-Networking.dellos-ecmp
